# Generated by Django 3.2.3 on 2021-05-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ranobe_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranobe',
            name='image',
            field=models.CharField(max_length=300),
        ),
    ]
