# Generated by Django 3.2.3 on 2021-05-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ranobe_App', '0002_alter_ranobe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranobe',
            name='editor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ranobe',
            name='englishName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ranobe',
            name='japaneseName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ranobe',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ranobe',
            name='statusOfTitle',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ranobe',
            name='statusOfTranslate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ranobe',
            name='translator',
            field=models.CharField(max_length=50),
        ),
    ]
