# Generated by Django 3.2.3 on 2021-05-24 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ranobe_App', '0004_auto_20210524_1336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
